development:
  default_emaiL: info@dubleds.com
  default_host: dubleds.com

  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: ENV['GMAIL_USERNAME']
    password: ENV['GMAIL_PASSWORD']

test:
  default_emaiL: info@dubleds.com
  default_host: dubleds.com

  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: ENV['GMAIL_USERNAME']
    password: ENV['GMAIL_PASSWORD']

staging:
  default_emaiL: info@dubleds.com
  default_host: dubleds.com

  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: ENV['GMAIL_USERNAME']
    password: ENV['GMAIL_PASSWORD']

production:
  default_emaiL: info@dubleds.com
  default_host: dubleds.com

  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: ENV['GMAIL_USERNAME']
    password: ENV['GMAIL_PASSWORD']