development:
  default_emaiL: info@dubleds.com
  default_host: dubleds.com

  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: info@dubleds.com
    password: letdubinn0w

test:
  default_emaiL: info@dubleds.com
  default_host: dubleds.com

  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: info@dubleds.com
    password: letdubinn0w

staging:
  default_emaiL: info@dubleds.com
  default_host: dubleds.com

  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: info@dubleds.com
    password: letdubinn0w

production:
  default_emaiL: info@dubleds.com
  default_host: dubleds.com

  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: info@dubleds.com
    password: letdubinn0w