development:
  access_key_id: <%= ENV['S3_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: dubledsprod
  directory: dubledsprod
  host: http://dubledsprod.s3-website-us-east-1.amazonaws.com/
  region: us-east-1

test:
  access_key_id: <%= ENV['S3_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: dubledsprod
  directory: dubledsprod
  host: http://dubledsprod.s3-website-us-east-1.amazonaws.com/
  region: us-east-1

staging:
  access_key_id: <%= ENV['S3_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: dubledsprod
  directory: dubledsprod
  host: http://dubledsprod.s3-website-us-east-1.amazonaws.com/
  region: us-east-1

production:
  access_key_id: <%= ENV['S3_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: dubledsprod
  directory: dubledsprod
  host: http://dubledsprod.s3-website-us-east-1.amazonaws.com/
  region: us-east-1