development:
  access_key_id: AKIAI5SWJWCFFJU6EPWQ
  secret_access_key: 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
  bucket: dubledsprod
  directory: dubledsprod
  host: http://dubledsprod.s3-website-us-east-1.amazonaws.com/
  region: us-east-1

test:
  access_key_id: AKIAI5SWJWCFFJU6EPWQ
  secret_access_key: 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
  bucket: dubledsprod
  directory: dubledsprod
  host: http://dubledsprod.s3-website-us-east-1.amazonaws.com/
  region: us-east-1

staging:
  access_key_id: AKIAI5SWJWCFFJU6EPWQ
  secret_access_key: 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
  bucket: dubledsprod
  directory: dubledsprod
  host: http://dubledsprod.s3-website-us-east-1.amazonaws.com/
  region: us-east-1

production:
  access_key_id: AKIAI5SWJWCFFJU6EPWQ
  secret_access_key: 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
  bucket: dubledsprod
  directory: dubledsprod
  host: http://dubledsprod.s3-website-us-east-1.amazonaws.com/
  region: us-east-1